### ISSUE TITLE
Assets are not attached to releases

### ISSUE THREAD

**Issue by qcloutier2** [semantic-release/github#234]
This is more of a question than an issue since I'm probably doing something wrong, but... I can't for the life of me get this to attach some assets to a release.

These are the relevant bits of my .releaserc.yaml:
```
.....
publish:
  - path: '@semantic-release/exec'
    cmd: 'VERSION="${nextRelease.gitTag}" ./release.sh'
  - '@semantic-release/github'
plugins:
  - - '@semantic-release/github'
    - assets:
      - path: 'build/darwin_amd64'
        label: myapp for macOS
```

"myapp" is built in a previous job and the workspace is persisted over to the current job (I've verified that it is actually persisting).

The release gets created without any errors, but the assets are nowhere to be found. Is there something I'm missing?
