### ISSUE TITLE
Replace Travis with GitHub Actions, remove codecov

### ISSUE THREAD

**Issue by gr2m** [semantic-release/github#289]
We want to do some maintenance to the @semantic-release repository, starting with replacing Travis with GitHub Actions.

@travi here is my current plan, does it cover everything? I'd do it manually in this repository, confirm that we didn't miss anything, then codify it for the remaining repositories using https://github.com/gr2m/mutate-github-repositories-cli

1. Delete `.travis` file
2. Remove Travis & Codecov badges from README.
3. Enforce 100% code coverage by updating `package.json`

   ```diff
      "nyc": {
        "include": [
          "lib/**/*.js",
          "index.js"
        ],
        "reporter": [
          "json",
          "text",
          "html"
        ],
   -    "all": true
   +    "all": true,
   +    "check-coverage": true,
   +    "branches": 100,
   +    "lines": 100,
   +    "functions": 100,
   +    "statements": 100
      },
   ```

4. Create `.github/workflows/test.yml` with the following content

   ```yml
   name: Test
   "on":
     push:
       branches:
         - master
         - next
         - beta
         - *.x
     pull_request:
       types:
         - opened
         - synchronize
   jobs:
     test:
       runs-on: ubuntu-latest
       strategy:
         matrix:
           node_version:
             - 10.8
             - 12
             - 14
       steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v1
           with:
             version: "${{ matrix.node_version }}"
         - run: npm install
         - run: npm run test
   ```

5. Create `.github/workflows/release.yml` with the following content

   ```yml
   on:
     push:
       branches:
         - master
         - next
         - beta
         - "*.x" # maintenance releases such as 15.x
   
   name: Release
   jobs:
     build:
       name: release
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v1
           with:
             node-version: 12
         - run: npm install
         - run: npx semantic-release
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
   ```

6. Add secret to the @semantic-release org: `NPM_TOKEN` (publish token for https://www.npmjs.com/~semantic-release-bot)

7. Remove Codecov app installation and required status check from branch protection
