### ISSUE TITLE
Can't publish a whole directory

### ISSUE THREAD

**Issue by jtuchel** [semantic-release/github#441]
I want to publish a whole directory (the build directory) on a Github release using semantic-release but unfortunately it releases each build file as a single asset.

For reproduction:

- I'm using the Vue CLI to generate a project `vue create foo`
- Install semantic-release as a dev dependency `npm install --save-dev semantic-release`
- Install the Github plugin for semantic-release `npm install @semantic-release/github -D`
- Create a `.releaserc.json` with the content

```json
    {
        "plugins":[
          "@semantic-release/commit-analyzer",
          "@semantic-release/release-notes-generator",
          [
            "@semantic-release/github",
            {
              "assets":[
                {
                  "path":"dist",
                  "label":"foo-${nextRelease.gitTag}"
                }
              ]
            }
          ]
        ]
      }
```

- Inside the *package.json* set the `version` key to `0.0.0-development`
- Create a *.github/workflows* directory with the workflow *ci.yml*

```yml
    name: CI
    
    on:
      push:
        branches:
          - main
    
    jobs:
      ci:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
    
          - name: Setup Node
            uses: actions/setup-node@v2
            with:
              node-version: 16.x
    
          - name: Install dependencies
            run: npm install
    
          - name: Run build
            run: npm run build
    
          - name: Release
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: npx semantic-release --branches main
```

- Commit and push it with `feat: pushed`

Yes it did make a release but it unfortunately didn't publish the whole *dist* directory.

![image](https://user-images.githubusercontent.com/92626738/140651229-61e0429e-dbb0-4e9f-a3ae-3d5394ab3d38.png)

It simply published each file as a single asset because it wasn't able to find the *dist* directory

![image](https://user-images.githubusercontent.com/92626738/140651238-1e672bce-c735-4285-8d70-5eba8eeace35.png)

How can I fix that?

---

Adding the step

```yml
      - name: Log
        run: ls
```

shows that the *dist* directory exists

![image](https://user-images.githubusercontent.com/92626738/140660618-7b517ceb-18a5-49fb-99ef-2a233ce0b8df.png)
