### ISSUE TITLE
feature request: Support using GitHub's release notes generator

### ISSUE THREAD

**Issue by ankush** [semantic-release/github#521]
Github's create release API supports use of their release notes generator by passing `generate_release_notes` boolean value. 

- https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
- https://docs.github.com/en/rest/releases/releases#create-a-release

A separate API to generate notes is also available:

https://docs.github.com/en/rest/releases/releases#generate-release-notes-content-for-a-release

**Comment by ankush** [comment]
Solves this with simple GH CLI script

```yaml
jobs:
  regen-notes:
    name: 'Regenerate release notes'
    runs-on: ubuntu-latest

    steps:
    - name: Update notes
      run: |
        NEW_NOTES=$(gh api --method POST -H "Accept: application/vnd.github+json"  /repos/org/repo/releases/generate-notes  -f tag_name=$RELEASE_TAG | jq -r '.body')
        RELEASE_ID=$(gh api -H "Accept: application/vnd.github+json" /repos/org/repo/releases/tags/$RELEASE_TAG | jq -r '.id')
        gh api --method PATCH -H "Accept: application/vnd.github+json" /repos/org/repo/releases/$RELEASE_ID -f body=$NEW_NOTES

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_TAG: ${{ github.event.release.tag_name }}
```
