### ISSUE TITLE
unauthenticated: User cannot be authenticated with the token provided on github action

### ISSUE THREAD

**Issue by qualle-admin** [semantic-release/github#566]
I am using a github action to publish a github package with `semantic-release` version `19.0.5`

I am positive the token I am setting on the environment is correct and `npm publish` works on my local with the same token.

Workflow file:

```
name: Release Package

on:
  push:
    branches: master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: |
          npm install -g yarn
          yarn
          yarn build

      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

```

Logs:

```
'npm notice 📦  @my-user/my-package@1.0.0\n' +
    'npm notice === Tarball Contents === \n' +
    'npm notice 394B  README.md         \n' +
    'npm notice 515B  dist/index.js     \n' +
    'npm notice 635B  dist/index.umd.cjs\n' +
    'npm notice 1.5kB dist/vite.svg     \n' +
    'npm notice 2.6kB package.json      \n' +
    'npm notice === Tarball Details === \n' +
    'npm notice name:          @my-user/my-package                       \n' +
    'npm notice version:       1.0.0                                   \n' +
    'npm notice filename:      @my-user/my-package-1.0.0.tgz             \n' +
    'npm notice package size:  2.7 kB                                  \n' +
    'npm notice unpacked size: 5.6 kB                                  \n' +
    'npm notice shasum:        afc773986369204a525a71b03048b117ce6e56a1\n' +
    'npm notice integrity:     sha512-FoH9NWIjDXr/r[...]VHR43oGMR1yyQ==\n' +
    'npm notice total files:   5                                       \n' +
    'npm notice \n' +
    'npm notice Publishing to [https://npm.pkg.github.com/\n](https://npm.pkg.github.com//n)' +
    'npm ERR! code E401\n' +
    'npm ERR! 401 Unauthorized - PUT https://npm.pkg.github.com/@my-user%2fmy-package - unauthenticated: User cannot be authenticated with the token provided.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /home/runner/.npm/_logs/2022-12-01T09_13_42_317Z-debug-0.log',
```
