### ISSUE TITLE
HELP - ERROR - Write access to repository not granted

### ISSUE THREAD

**Issue by jdgabriel** [semantic-release/github#578]
I'm configuring semantic-release in a repo, but I get the error:

### ERROR
```bash
[2:08:16 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[2:08:18 PM] [semantic-release] › ✔  Run automated release from branch main on repository https://github.com/jdgabriel/teste-deleting.git
[2:08:18 PM] [semantic-release] › ✘  The command "git push --dry-run --no-verify https://[secure]@github.com/jdgabriel/teste-deleting.git HEAD:main" failed with the error message remote: Write access to repository not granted.
fatal: unable to access 'https://github.com/jdgabriel/teste-deleting.git/': The requested URL returned error: 403.
[2:08:18 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[2:08:18 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
(node:1760) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[2:08:19 PM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #2.
[2:08:21 PM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #2: https://github.com/jdgabriel/teste-deleting/issues/2#issuecomment-1[37](https://github.com/jdgabriel/teste-deleting/actions/runs/3874542745/jobs/6605883634#step:6:38)5676907.
[2:08:21 PM] [semantic-release] › ✘  EGITNOPERMISSION Cannot push to the Git repository.
[2:08:21 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
semantic-release cannot push the version tag to the branch main on the remote Git repository with URL https://[secure]@github.com/jdgabriel/teste-deleting.git.

This can be caused by:

    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)

SemanticReleaseError: Cannot push to the Git repository.
    at default (file:///home/runner/work/teste-deleting/teste-deleting/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (file:///home/runner/work/teste-deleting/teste-deleting/node_modules/semantic-release/index.js:101:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.default (file:///home/runner/work/teste-deleting/teste-deleting/node_modules/semantic-release/index.js:275:22)
    at async default (file:///home/runner/work/teste-deleting/teste-deleting/node_modules/semantic-release/cli.js:[55](https://github.com/jdgabriel/teste-deleting/actions/runs/3874542745/jobs/6605883634#step:6:56):5) {
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `main` on the remote Git repository with URL `https://[secure]@github.com/jdgabriel/teste-deleting.git`.\n' +
    '\n' +
    'This can be caused by:\n' +
    ' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
    ' - the repository being unavailable\n' +
    ' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
}npm ERR! Lifecycle script `semantic-release` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @pso-easynr10/server@0.0.0 
npm ERR!   at location: /home/runner/work/teste-deleting/teste-deleting/packages/server 
Error: Process completed with exit code 1.
```

Token scope changed to all after error:
### Personal Token
![image](https://user-images.githubusercontent.com/47068314/211327889-e3b5d852-6b60-4506-bbe1-10d102781fca.png)

### Github Action
```yml
name: Create new release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
```
Token has created in repository with name `GH_TOKEN`

The error still persists. How to solve?
