### ISSUE TITLE
unauthenticated: User cannot be authenticated with the token provided (GitHub action, GitHub packages)

### ISSUE THREAD

**Issue by missingzero** [semantic-release/github#601]
I'm trying to use GitHub actions to publish a **GitHub package** on my **private repo**
However, the **automatic GitHub token** doesn't seem to carry the permissions for publishing a package, even though I explicitly set them in the workflow 🤔 

I've come across #566, but the solution of removing `@semantic-release/npm` doesn't work for me, as it **wouldn't publish** a package at all.

### Workflow
```yml
name: release

on:
  push:
    branches: main

permissions:
  contents: write
  packages: write
  issues: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm install --save-dev @semantic-release/changelog @semantic-release/git
      - run: npm run format
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Logs
```sh
'npm notice \n' +
'npm notice 📦  @nullcade/semantic-release-config@1.1.2\n' +
'npm notice === Tarball Contents === \n' +
'npm notice 3.7kB CHANGELOG.md     \n' +
'npm notice 1.1kB LICENSE.md       \n' +
'npm notice 643B  README.md        \n' +
'npm notice 0B    dist/index.d.ts  \n' +
'npm notice 846B  dist/index.js    \n' +
'npm notice 458B  dist/index.js.map\n' +
'npm notice 1.3kB package.json     \n' +
'npm notice === Tarball Details === \n' +
'npm notice name:          @nullcade/semantic-release-config          \n' +
'npm notice version:       1.1.2                                      \n' +
'npm notice filename:      @nullcade/semantic-release-config-1.1.2.tgz\n' +
'npm notice package size:  3.2 kB                                     \n' +
'npm notice unpacked size: 8.1 kB                                     \n' +
'npm notice shasum:        7fbad25813c7d2e0f4beccc93aefb1a27[221](https://github.com/nullcade/semantic-release-config/actions/runs/4351521726/jobs/7603266183#step:8:222)bbde   \n' +
'npm notice integrity:     sha512-McBftRJzXTn0y[...]SbOEOCTh/Osxw==   \n' +
'npm notice total files:   7                                          \n' +
'npm notice \n' +
'npm notice Publishing to [https://npm.pkg.github.com\n](https://npm.pkg.github.com/n)' +
'npm ERR! code E401\n' +
'npm ERR! 401 Unauthorized - PUT https://npm.pkg.github.com/@nullcade%2fsemantic-release-config - unauthenticated: User cannot be authenticated with the token provided.\n' +
'\n' +
'npm ERR! A complete log of this run can be found in:\n' +
'npm ERR!     /home/runner/.npm/_logs/2023-03-07T07_02_40_529Z-debug-0.log'
```
