### ISSUE TITLE
I can't this make this works. but don't know why.

### ISSUE THREAD

**Issue by henri9813** [semantic-release/github#846]
Here is my configuration,

```
{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/github",
      {
        "assets": [
          { "path": "dist" }
        ]
      }
    ],
    "@semantic-release/github"
  ],
  "publish": ["@semantic-release/github"],
  "verifyConditions": ["@semantic-release/github"],
  "success": false,
  "fail": false,
  "npmPublish": false
}
```

What's wrong with this ? 

<img width="1432" alt="image" src="https://github.com/semantic-release/github/assets/4645967/be0e2890-5b1e-4596-b21b-13712e478a79">

Here is my workflow
```
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs:
      - macos-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: dist

      - run: find .
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: "configure semantic-release"
        run: npm install -D semantic-release @semantic-release/github

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

And i confirm I got file in my `dist` directory. 

```
Run find .
.
./README.md
./dist
./dist/iPingTray.dmg
./dist/iPingTray.dmg/iPingTray.dmg
```

Do you know why ?
